
portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - /home/dztang/cluster/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
   - tomcatThree:tomcat3

tomcatOne:
  image: mytomcat:8.0
  volumes:
   - /home/dztang/tomcat_mapping/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/dztang/tomcat_mapping/webapps:/usr/local/tomcat/webapps
   - /home/dztang/tomcat_mapping/logs:/usr/local/tomcat/logs

tomcatTwo:
  image: mytomcat:8.0
  volumes:
   - /home/dztang/tomcat_mapping/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/dztang/tomcat_mapping/webapps:/usr/local/tomcat/webapps
   - /home/dztang/tomcat_mapping/logs:/usr/local/tomcat/logs

tomcatThree:
  image: mytomcat:8.0
  volumes:
   - /home/dztang/tomcat_mapping/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/dztang/tomcat_mapping/webapps:/usr/local/tomcat/webapps
   - /home/dztang/tomcat_mapping/logs:/usr/local/tomcat/logs
