portal:
  image: mkodockx/docker-nginx-proxy
  container_name: nginx

  ports:

   - "8080:80"

  volumes:

   - /var/run/docker.sock:/tmp/docker.sock:ro 

  links:

   - tomcat  


mysql:

  image: mysql/mysql-server:5.7

  ports:

   - "3306:3306"

  container_name: mysql5.7

  volumes:

   - /home/dztang/mysql_data:/var/lib/mysql

  env_file: /home/dztang/mysql.env



tomcat:

  image: mytomcat:8.0

  volumes:

   - /home/dztang/tomcat_mapping/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

   - /home/dztang/tomcat_mapping/webapps:/usr/local/tomcat/webapps

   - /home/dztang/tomcat_mapping/logs:/usr/local/tomcat/logs

  env_file: /home/dztang/comm.env
  
activemq-1:
  image: webcenter/activemq
  ports:
   - "8161:8161"
   - "61616:61616" 
   - "61613:61613" 
  volumes:
    - /home/dztang/active_mapping/data:/data/activemq 
    - /home/dztang/active_mapping/log:/var/log/activemq 
    - /home/dztang/active_mapping/conf:/opt/activemq/conf 
    - /home/dztang/active_mapping/lib/mysql-connector-5.1.38.jar:/opt/activemq/lib/optional/mysql-connector-5.1.38.jar 
    
  env_file: /home/dztang/activemq.env
   
activemq-2:
  image: webcenter/activemq
  ports:
   - "8162:8161"
   - "61617:61616" 
   - "61614:61613" 
  volumes:
    - /home/dztang/active_mapping/data:/data/activemq 
    - /home/dztang/active_mapping/log:/var/log/activemq 
    - /home/dztang/active_mapping/conf:/opt/activemq/conf 
    - /home/dztang/active_mapping/lib/mysql-connector-5.1.38.jar:/opt/activemq/lib/optional/mysql-connector-5.1.38.jar 
    
  env_file: /home/dztang/activemq.env
   